
import { Navigation } from '@/components/Navigation'
import './globals.sass'
import { Nunito } from 'next/font/google'
import { Footer } from '@/components/Footer'

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="ru">
            <body className={nunito.className}>
                <Navigation />
                <main className="wrapper">{children}</main>
                <Footer />
            </body>
        </html>
    )
}
